name: push‑image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: log in to registry
        uses: docker/login-action@v2
        with:
          registry: scr.scynettghana.com
          username: docker
          password: password

      - name: pull, tag and push hello‑world
        run: |
          docker pull hello-world
          docker tag hello-world scr.scynettghana.com/hello-world:latest
          docker push scr.scynettghana.com/hello-world:latest